### ISSUE TITLE
Weird javascript regression on UXP

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#264] opened 2018-04-24 21:42 UTC
As [reported at the forum](https://forum.palemoon.org/viewtopic.php?f=61&t=18967) Tutanota https://mail.tutanota.com does not work on `Basilisk 2018.04.23` and throws an error in the console: 

```
Unhandled rejection value@https://mail.tutanota.com/main-boot.js:1:183005
value@https://mail.tutanota.com/main-boot.js:1:182045
value@https://mail.tutanota.com/main-boot.js:1:181855
[...]
r/this.drainQueues@https://mail.tutanota.com/libs.js:30:1236
```

I did several tests and here are the results:

Browser | Result
------------------ | -- 
Pale Moon 27.9.0 | Ok 
Basilisk 2018.03.21 | Ok 
Firefox ESR 52.7.3 | Ok 
Pale Moon 28.0.0a1 / [[810a324]](https://github.com/MoonchildProductions/UXP/tree/810a3245a8c609c495be4dace044713b9717f0c0) | Fail
Basilisk 2018.04.23 | Fail
Basilisk UXP [CP1](https://github.com/MoonchildProductions/UXP/tree/FullFunction_CP1) | Fail
Basilisk UXP [[c28c5b7]](https://github.com/MoonchildProductions/UXP/tree/c28c5b704fb3f3af6e7846abd73f63da1e35921f) | Ok

Unfortunately my PC is too slow to bisect further...

**Comment by janekptacijarabaci** [comment] 2018-04-24 22:03
There is a function:
`Intl.DateTimeFormat`

AFAIK:
https://github.com/MoonchildProductions/UXP/commit/7686bceecff17f91758c8c6547a78e71ff3a8c38

**Comment by wolfbeast** [comment] 2018-04-24 23:03
@janekptacijarabaci I have no clue what you are trying to say...

**Comment by janekptacijarabaci** [comment] 2018-04-25 05:58
I'm sorry, for now, I can not say more, but - `master` without this commit https://github.com/MoonchildProductions/UXP/commit/7686bceecff17f91758c8c6547a78e71ff3a8c38:

![master](https://user-images.githubusercontent.com/2373486/39228370-5c80aa30-484d-11e8-9655-0ce36e0a46d7.png)

**Comment by wolfbeast** [comment] 2018-04-25 06:16
PLEASE EXPLAIN

"There is a function x()"
"I cannot say more, but screenshot"
What the hell am I supposed to get from that?

**Comment by wolfbeast** [comment] 2018-04-25 06:27
OK, I'm backing out that one commit - I'm not even sure where it came from but it seems to be incomplete.

**Comment by JustOff** [comment] 2018-04-25 08:37
> OK, I'm backing out that one commit

I confirm this resolves problem at https://mail.tutanota.com

> I'm not even sure where it came from but it seems to be incomplete.

It seems it came from [Moebius: Avoid calling slice in self-hosted code. DiD](https://github.com/MoonchildProductions/moebius/commit/f61b04666c3702c00c36005bd0ff63553ada33e5#diff-932ef8de19eae550f116ad55632c6aa5), but with extra incomplete changes from the diff between UXP and Moebius.

@janekptacijarabaci, please unhide the magic - how did you find the cause (this particular commit) so fast?! It's not like you were doing a search by bisecting the tree and compiling.

**Comment by janekptacijarabaci** [comment] 2018-04-25 08:45
It should be just a guideline, I didn't have time for anything else...

This is the function:
`Intl.DateTimeFormat`
that is called in:
`https://mail.tutanota.com/main-boot.js:1:183005`

And I compared the difference between:
https://github.com/MoonchildProductions/UXP/tree/FullFunction_CP1
and
https://github.com/MoonchildProductions/UXP/tree/c28c5b704fb3f3af6e7846abd73f63da1e35921f
thanks @JustOff !

I'm sorry but using `bisect` isn't applicable to me either...
IMHO: An without an archive of previous builds it will not be better. I suggested it a long time ago. Otherwise, I can't help too much...

**Comment by wolfbeast** [comment] 2018-04-25 08:52
> IMHO: And without an archive of previous builds it will not be better. I suggested it a long time ago. Otherwise, I can't help too much...

We can't make and archive a build for every commit change. Do you have any idea what the storage requirements for that are?

**Comment by JustOff** [comment] 2018-04-25 09:02
I understand we can't afford archiving the builds from every commit, but I think even some compromise solution could be very helpful. Say, for example, daily builds for the last month + weekly builds for the last year require only 1.5Gb + 2.6Gb = ~4Gb. The only question is how to manage it.

**Comment by janekptacijarabaci** [comment] 2018-04-25 09:03
> Do you have any idea what the storage requirements for that are?

Builds should have a backup at least on a daily basis (at least if needed for it - e.g. on FTP page - even with a password).
I don't have a better idea - but someone might have other ideas... :-)

**Comment by wolfbeast** [comment] 2018-04-25 09:27
> Say, for example, daily builds for the last month + weekly builds for the last year require only 1.5Gb + 2.6Gb = ~4Gb. 

No. Even if I save minimal packaged builds + their symbols I'm looking at (230Mx7 + 230Mx52) = 13.5GB. Only going 1 week back with dailies is also pointless, because regressions and bugs are usually NOT caught within 7 days.
On top, I want to avoid having to build daily, because it'll pretty much mean needing to have a machine up and active 24/7 -- at which point operational costs for that machine alone (elec) will weigh in too heavily.

**Comment by wolfbeast** [comment] 2018-04-25 11:08
I've re-landed the patch with only the proper lines of code in place. I think what may have happened is me not paying attention with a merge conflict and ending up grafting a lot more from Möbius than I should have.

**Comment by wolfbeast** [comment] 2018-04-25 11:31
confirmed the login screen pops up with all patches applied. considering solved.

**Closed by wolfbeast** 2018-04-25 11:31 UTC
Labels: Regression
