### ISSUE TITLE
Problem processing a page with a lot of images

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#625] opened 2018-07-11 18:08 UTC
As reported [on forum](https://forum.palemoon.org/viewtopic.php?f=63&t=19629) following page have problem loading and closing (very long time): 

http://ftp.belnet.be/mirror/pclinuxonline.com/pclinuxos/apt/pclinuxos/64bit/RPMS.x86_64/

| Browser | Loading | Closing |
|--|--|--|
|PM27 | good | good |
|Firefox ESR45 | good | good |
|Firefox ESR52 (e10s=off) | good | bad |
|PM28a2 2018.05.25 | good | bad |
|Basilisk 2018.06.01 | good | bad |
|PM28a4 2018.06.19  | bad | bad |
|Basilisk 2018.07.11 | bad | bad |
|PM28b3 2018.07.11 | bad | bad |

So in fact we have two issues here:
- [x] 1) Closing problem: regression log - https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=b2dbee5ca727e87bdaeab9ab60fb83df2a9846a2&tochange=63be002b4a803df1122823841ef7633b7561d873
~~My suspect is [bug #1258436](https://bugzilla.mozilla.org/show_bug.cgi?id=1258436).~~
- [ ] 2) Loading problem: it seems something between 2018.06.01 and 2018.06.19 in UXP repo.
UPD: Unfortunately the loading issue turned out to be quite unstable: sometimes I see it with the older builds too, sometimes the latest ones load without any problems, so the UXP regression range above can't be  trusted.

**Comment by janekptacijarabaci** [comment] 2018-07-11 19:22
Regression of bug 1258436 - same problem (AFAIK).

**Comment by JustOff** [comment] 2018-07-11 19:32
> Regression of bug 1258436 - same problem

Sorry, it's not entirely clear what you mean: is it a wrong suspect or a confirmed cause of regression?

**Comment by janekptacijarabaci** [comment] 2018-07-11 19:36
I'm sorry. **Revert** of bug 1258436 - same problem.

**Comment by JustOff** [comment] 2018-07-11 19:41
Thanks, then it's a wrong suspect :disappointed:

**Comment by janekptacijarabaci** [comment] 2018-07-11 19:46
> it's a wrong suspect

I also don't see anything else...

**Comment by wolfbeast** [comment] 2018-07-11 21:52
Potentially https://bugzilla.mozilla.org/show_bug.cgi?id=1256084 ?

**Comment by wolfbeast** [comment] 2018-07-11 22:03
As for the loading, there were a few changes in that range that touch nsIContentPolicy which could cause load slowdowns if there's a bug.,

**Comment by JustOff** [comment] 2018-07-12 10:07
Unfortunately the loading issue turned out to be quite unstable: sometimes I see it with the older builds too, sometimes the latest ones load without any problems, so the UXP regression range above can't be  trusted.

However, I found out that if you disable images (`permissions.default.image -> 2`), both loading and closing problems disappear.

> Potentially https://bugzilla.mozilla.org/show_bug.cgi?id=1256084 ?

Hmm, it seems to me it's hardly related.

**Comment by janekptacijarabaci** [comment] 2018-07-12 11:00
> Unfortunately the loading issue turned out to be quite unstable: sometimes I see it with the older builds too, sometimes the latest ones load without any problems, so the UXP regression range above can't be trusted.

I agree.

**Comment by janekptacijarabaci** [comment] 2018-07-12 11:08
Ad Closing: I've probably tried all potentially bugs. I don't know...

**Comment by mattatobin** [comment] 2018-07-12 11:18
So if disabling images prevents the issue this points to the image decoders possibly off screen surface cache (if i am using the correct term for it) and deallocation of them as points of intrest.

**Comment by wolfbeast** [comment] 2018-07-12 12:02
> Potentially https://bugzilla.mozilla.org/show_bug.cgi?id=1256084 ?
> Hmm, it seems to me it's hardly related.

As far as I can tell this is a layout bottleneck -- so if something changes reflow behavior, it's quite possible it influences things. If disabling images improves things, then it's something about having styling 75,000 lines of image+hidden markers+text that is a problem. This may be our old friend of splitting up the lines into sections for visual selection.
I verified it's not network performance, the html loads in 3 seconds, the image in 0.4. It's properly cached and everything.

**Comment by wolfbeast** [comment] 2018-07-12 12:17
Running the profiler in FF nightly (since it suffers from the same) all the time is taken up by "applying style changes" so yes, it's a styling/reflow problem with such a large element.

**Comment by JustOff** [comment] 2018-07-12 13:03
> Running the profiler in FF nightly (since it suffers from the same)

You mean the closing tab/browser issue?

**Comment by wolfbeast** [comment] 2018-07-12 13:33
I mean FF nightly takes minutes to open that page as well. Closing the tab chokes too, but that's hidden from the user because of e10s.

**Comment by wolfbeast** [comment] 2018-07-12 13:37
The loading issue also occurs on 27.9, so it's not something new and not a regression.

**Comment by JustOff** [comment] 2018-07-12 13:43
But 27.9 opens this page within 15-20 seconds and has no issue closing the tab, while UXP needs 3-5+ minutes for the both operations. The same was reported on forum, so I'd say it's regression.

**Comment by wolfbeast** [comment] 2018-07-12 13:48
Sorry but 27.9 does NOT open the page in 15-20 seconds. It takes quite a few minutes, during which one core remains 100% loaded. Only if I disable images, it will load in ~25 seconds.

**Comment by wolfbeast** [comment] 2018-07-12 13:55
Okay -- interesting tidbit: @JustOff your 27.9 probably has hardware acceleration DISabled, because it renders in the indicated time in that case.

**Comment by JustOff** [comment] 2018-07-12 13:58
It's very strange, my 10-years PC needs no more than 15-20 second with 27.9 regardless of images are disabled or not. It can take longer only with ad-blocking extensions enabled, but not using a clean profile.

> our 27.9 probably has hardware acceleration DISabled
GPU Accelerated Windows	1/1 Direct3D 11 (OMTC)

**Comment by wolfbeast** [comment] 2018-07-12 14:10
Your 10-years old PC probably has parts of the HWA disabled (probably layers) even if your overall window uses D3D 11. For me, HWA enabled on 27.9 takes minutes, with it disabled it takes about 20 seconds with or without images.
UXP chokes either way, so does Firefox. I opened an [upstream bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1475222) to see what they say, since it's a layout perf issue and they have better tools available to home in on these things.

**Comment by THEtomaso** [comment] 2018-07-12 15:33
> 27.9 opens this page within 15-20 seconds and has no issue closing the tab, while UXP needs 3-5+ minutes

I can confirm the same loading times on my Win8.1 computer.
From "Waiting for".. till "Done":
Pale Moon v27.9.3,x64: 20 seconds
Pale Moon v28.0.0b2,x64: 4 minutes 15 seconds

**Comment by mattatobin** [comment] 2019-04-21 22:30
Can any of @janekptacijarabaci 's work be salvaged to resolve this?

**Comment by wolfbeast** [comment] 2019-08-12 22:01
> Can any of @janekptacijarabaci 's work be salvaged to resolve this?

No, because his work was stuff that's already in our tree at this point and did not fix the issue for Mozilla either.

A propos, Mozilla has "accidentally" fixed this issue very recently, likely in either [Bug 1566945](https://bugzilla.mozilla.org/show_bug.cgi?id=1566945) (most likely candidate) or [Bug 1300293](https://bugzilla.mozilla.org/show_bug.cgi?id=1300293)

**Comment by wolfbeast** [comment] 2019-08-20 09:44
I've looked further into this and it seems this is extremely intermittent in the implementation. Trying to mozregress this went all over the place and is unreliable, so it's likely a timing-dependent race condition that I can't pinpoint. I also think this wasn't fixed in Firefox since nightly still shows intermittently long delays, but I'm not going to bother reopening the BZ bug for it, as it will not be fixed there. This is as good as it's gonna get for this corner case; marking this wontfix since there's no clear path forward here.

**Closed** 2019-08-20 09:44 UTC
Labels: C: Layout, Performance, Research, Won't Fix
