### ISSUE TITLE
Problem with adblockers

### ISSUE THREAD

**Issue by Felipefpl** [MoonchildProductions/UXP#752] opened 2018-09-05 05:28 UTC
Got the latest version of basilisk and the browser hangs/locks itself for some time when it's blocking ads, i tried latest abprime, adblock plus and adblock (and its clones). I dont remember if it hanged with ublock and its clones but it's likely to have happened too. I didnt have this problem with pale moon 27. I know this happens when the lists are being updated but i dont understand why this happens outside this situation.

**Comment by wolfbeast** [comment] 2018-09-05 17:33
Please take your question to the [forum](https://forum.palemoon.org/)

**Comment by Felipefpl** [comment] 2018-09-07 13:11
This isnt a question, it's a bug report since this is a behavior not seen in another browsers so this is something that isnt working as it should.

**Comment by wolfbeast** [comment] 2018-09-07 13:45
Well if you want me to treat this as a bug report, then I will. First step will still be to go to the forum, provide troubleshooting information, and get confirmed that it is indeed a bug with the platform/browser.
Part of that will be to provide details about your environment and a copy of troubleshooting information from the browser.

**Comment by Felipefpl** [comment] 2018-09-08 20:08
Thank you for bringing this back from closed, i posted at the forum as you requested.

https://forum.palemoon.org/viewtopic.php?f=61&t=20340&p=151723#p151723

**Comment by wolfbeast** [comment] 2018-09-12 13:53
Marking this NI and on hold since no further information was yet supplied.

**Comment by wolfbeast** [comment] 2019-03-30 14:36
More information was never provided. Closing as WFM.

**Closed by wolfbeast** 2019-03-30 14:36 UTC
Labels: Hang, More info needed, On Hold, Works for me
