### ISSUE TITLE
Restore gkmedias library

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1453] opened 2020-02-19 13:02 UTC
Is we want to be able to split out the media code for #1451 we need to restore what Mozilla removed in [1216444](https://bugzilla.mozilla.org/show_bug.cgi?id=1216444), then work through what is broken in terms of exports to restore shared building.

**Comment by mattatobin** [comment] 2020-02-20 00:01
Duplicate of #61

**Closed by mattatobin** 2020-02-20 00:01 UTC
Labels: C: Build System, C: Media
