### ISSUE TITLE
browser.tabs.tabMaxWidth /browser.tabs.tabMinWidth setting are not working

### ISSUE THREAD

**Issue by shellye5** [MoonchildProductions/UXP#819] opened 2018-10-07 16:41 UTC
try setting them to 80 or whatever you like.
Won't work used to before though and was super helpful

Stable and beta 28 with new profile

**Comment by wolfbeast** [comment] 2018-10-07 19:07
Duplicate of #410

**Closed by wolfbeast** 2018-10-07 19:07 UTC
