### ISSUE TITLE
Pale Moon 28 customization of toolbar issue

### ISSUE THREAD

**Issue by win7-7** [MoonchildProductions/UXP#242] opened 2018-04-23 20:22 UTC
In new profile with Pale Moon 28 master branch build without yet any modifications you can use customization of toolbar only once but after that selection of customization option deactivates/grays itself and won't let you customize PM28 toolbar anymore. Tag #121.

**Comment by JustOff** [comment] 2018-04-23 20:26
I can't reproduce this issue.

**Comment by mattatobin** [comment] 2018-04-23 20:37
Neither can I

**Comment by win7-7** [comment] 2018-04-23 21:40
I didn't build from today master branch but still there does not seems to be recent commits that should fix this issue.

I built it from master branch that was about 4 days old.

There is also download button stopping functioning at same time as customization of toolbar function (after one time usage) that seems to be related to this issue.

I did meet all requirements for UXP platform building, Visual Studio 2015 etc. Not sure why it is happening on this particular PM28 build. There is also issue with bookmark toolbar being invisible on toolbar and coming back visible if I check it off and on then it will stay until browser restart. Bookmark menu stays always on its place.

**Comment by janekptacijarabaci** [comment] 2018-04-24 05:55
Not confirmed for me (also).

I see a small bug in the code - I will fix it soon. But... it should not affect your problem - maybe (they are synonyms - even if it's not right).

And please check the Browser Console and if you see any error you can screenshot.

**Comment by win7-7** [comment] 2018-04-24 10:11
Error console was not included in default build of PM in UXP so I installed Error Console 2 addon which somewhat seems to function at least.

This is error related to download button if I use customization of toolbar and then press download button using JustOff Error Console 2 addon. 

![error](https://user-images.githubusercontent.com/16404264/39180734-56b6f448-47c0-11e8-81fa-c0bdffa56472.PNG)

I haven't however found direct error related to customization of toolbar not functioning after one time usage.

**Comment by JustOff** [comment] 2018-04-24 10:30
> Something has gone terribly wrong with your build.

Definitely wrong! + [Devtools is enabled by default](https://github.com/MoonchildProductions/UXP/commit/c1852a54a598950f01c877875af39e4c31c55455).

**Comment by wolfbeast** [comment] 2018-04-24 11:40
Marking this as invalid caused by wrong build.

**Closed** 2018-04-24 11:40 UTC
Labels: Invalid

**Comment by mattatobin** [comment] 2018-04-24 11:43
The Error Console has nothing to do with DevTools.

**Comment by JustOff** [comment] 2018-04-24 11:48
I know, I just meant that normal build of Pale Moon UXP has both of them.
