### ISSUE TITLE
browser.link.open_newwindow doesn't work properly for external links

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#971] opened 2019-02-13 04:22 UTC
This seems to be a Tycho -> UXP regression in the FE.
Looks like it may be related to the context now also being abused to pass "opener" flags from the back-end, making a simple comparison to known values fail.

Compare http://xref.palemoon.org/uxp-trunk/source/application/palemoon/base/content/browser.js#4411
and http://xref.palemoon.org/uxp-trunk/source/application/basilisk/base/content/browser.js#4741

**Comment by wolfbeast** [comment] 2019-02-15 13:05
PR #972 _should_ fix this. Landing this untested as an exception because of testing limitations in my work env. If people find it doesn't work while it should, we can re-open this issue.

**Comment by wolfbeast** [comment] 2019-02-21 10:02
Apparently this did not fix the issue. Reopening.

**Comment by adeshkp** [comment] 2019-04-25 18:00
This is not related to external links only and is reproducible with having something like `<a target="cool" href="http://palemoon.org/">PM</a>` in a page open in Pale Moon.

The issue here is that `browser.js`->`openURI` is called every time a link with a specific target is clicked in Pale Moon. It doesn't matter whether a window (tab) with the target name is already open in the browser or not.
As you know Basilisk is unaffected by this bug and it's behaviour is that it creates a new tab first time the link is clicked by calling openURI function. On subsequent clicks on the _same_ link (or different links with same target), it bypasses openURI call and loads the link directly in the already open tab.

My hunch is that Pale Moon is not able to query the browser to find the target window/tab, as it may be passing the wrong target name or not passing target at all and treating everything as `_blank`.

I was trying to fix this quickly and hoping to see this in 28.5.0, but now it's the end of the road for me. Don't know how to proceed further.

**Comment by FranklinDM** [comment] 2019-05-21 12:39
I think I've found the cause and solution to this issue.

When opening external links, an error is thrown to the console:
```
ReferenceError: can't access lexical declaration `referrer` before initialization  
browser.js:10975:37
	openURI chrome://browser/content/browser.js:10975:37
	handURIToExistingBrowser resource://app/components/nsBrowserContentHandler.js:687:3
	dch_handle resource://app/components/nsBrowserContentHandler.js:772:11
```
The problem seems to be the declaration of `referrer` here inside the switch block, case 2 (OPEN_NEWTAB):
https://github.com/MoonchildProductions/UXP/blob/41731a7f31a1724e74b32eb7be87de2719f977c3/application/palemoon/base/content/browser.js#L4484

Whereas `referrer` was already declared earlier inside the same function here:
https://github.com/MoonchildProductions/UXP/blob/41731a7f31a1724e74b32eb7be87de2719f977c3/application/palemoon/base/content/browser.js#L4442

A simplified example of what happened in loadURI:
```
function example(testcase) {
  let referrer = false;

  switch (testcase) {
    case 1:
       var uselessVariable = null;
      break;
    case 2:
       let referrer = false;
       return referrer;
      break;
    default:
       return referrer;
      break;
  }
}
example(3);
```
Running the above example in the JS Scratchpad will trigger the same error that happened to the openURI function.

Basilisk is not affected because it handles case 2 differently. My suggestion is to either remove the offending line in case 2 (has no effect on the flow because it is already defined earlier) or adapt the way Basilisk handles case 2. I can send a PR if requested.

**Comment by mattatobin** [comment] 2019-05-21 14:45
That is some good work.. If removing the second one on `Line 4484` has no effect (which it doesn't look like it does) except resolving this. Then sure, submit your PR, I will verify and merge.

Please have your commit titled as:
`Issue #[this issue number] - Fix browser.link.open_newwindow` functionality in Pale Moon`

**Comment by FranklinDM** [comment] 2019-05-22 12:08
**For external links:**
Quoting the reporter `AndTheWolf` from the [forum](https://forum.palemoon.org/viewtopic.php?f=3&t=20492&p=154712#p153163):
>No need for test pages. All you need to do to reproduce is set browser.link.open_newwindow.override.external to 1 (or set browser.link.open_newwindow.override.external to -1 AND set browser.link.open_newwindow to 1), and then, while PM is running, click on a link in an external application (an email client like Thunderbird, a text editor that recognizes links, an office program like Microsoft Office, LibreOffice, or Open Office, etc.) or click on an html document.

The link or document should open in the current tab with this patch in place (PM might have to be set as the default browser).

**For in-browser links:**
To see if there was a negative effect since it uses the same function, using @adeshkp's test case:
A. Open the HTML file in [issue971-inbrowser.zip](https://github.com/MoonchildProductions/UXP/files/3207221/issue971-inbrowser.zip).
B. Click on the `PM` link and compare the behavior when the pref `browser.link.open_newwindow` is set to:
(1) Link should open in current/same tab.
(2) Link should open in new window.
(3) Link should open in new tab.

**Comment by wolfbeast** [comment] 2019-05-22 15:18
The next unstable build on Windows later today should have this fixed.

**Closed** 2019-05-22 15:17 UTC
Labels: App: Pale Moon, Regression

**Comment by mattatobin** [comment] 2019-05-22 15:33
Do we want an uplift on this?

**Comment by wolfbeast** [comment] 2019-05-22 16:44
Maybe? I don't think this is critical, but it is a one-liner....

**Comment by adeshkp** [comment] 2019-05-22 17:01
My testing says issue is still present.

If you try my test case, clicking the link (with a target) multiple times will spawn multiple tabs in Pale Moon while clicking the link in Basilisk will open only one tab and subsequent clicks will trigger the load in the same open tab. This is regardless of the mentioned preference (set to default of 3 in both the browsers).

**Comment by FranklinDM** [comment] 2019-05-23 02:21
@adeshkp , I think that it's a separate issue since it is not related to external links - I've checked this and is slightly more involved but was able to get a working fix (I'll try to send a PR in a while).

It includes changes to both the openURI function passing an `aOpener` to the `loadOneTab` function inside the tabbrowser binding. `loadOneTab` and `addTab` both have to be modified to accept `aOpener` and set it as the new browser's opener.

**Comment by mattatobin** [comment] 2019-05-23 04:02
Well with these changes might be best to let them bake until july release.

@FranklinDM please create a second issue please.
