### ISSUE TITLE
Github stopped working like it did before

### ISSUE THREAD

**Issue by Felipefpl** [MoonchildProductions/UXP#864] opened 2018-11-06 04:58 UTC
Github now displays a msg saying it doesnt support old versions of firefox and tells to upgrade, i chose to ignore of course but now when i hover the mouse arrow over the link of an issue it doesnt show the title of the issue anymore, neither displays the full content of a commit's title when the one is too big to be displayed in the page.

I have win7 x64, no new extensions added and basilisk 11/4.

**Comment by ibuprophen1** [comment] 2018-11-06 16:14
A resolution to this issue looks like it was resolved in Waterfox recently on the https://github.com/MrAlex94/Waterfox/pull/784 pull request. 

Just wanted to make this known here... 


~Ibuprophen

**Comment by kn-yami** [comment] 2018-11-06 17:02
GitHub works fine in Pale Moon (no warnings and every thing works fine as far as I can tell) so I guess that they are limiting the web site features when they detect an older version of Firefox. Pale Moon is probably detected separately. That Watefox pull request only adds an UAO for `github.com`. GitHub should probably be contacted, because if they have no problems with Pale Moon there is no reason for them to limit other UXP applications (I guess they could simply detect `Goanna/4.1` or higher).

**Comment by grahamperrin** [comment] 2018-11-06 23:47
Without an override: you might also find that **Edit** is ineffective in e.g. the menu for a comment.

**Comment by mattatobin** [comment] 2018-11-07 01:07
Well it is about time for a bump of the Firefox compat version anyway in most cases.

**Comment by wolfbeast** [comment] 2018-11-07 05:16
not-logged-in users won't have edit capabilities.

Also, I cannot reproduce any issues with github. Everything works just fine with the default Firefox compatmode for me.

**Comment by mattatobin** [comment] 2018-11-07 05:37
It depends.. I also got it on Borealis and a new profile in Pale Moon but it hasn't shown up on my normal profile and logged in session..

I think it is being staggered out to users or something.. Still might be a good idea to update the Fx version slice to 60 for github or across the board..

**Comment by wolfbeast** [comment] 2018-11-07 05:41
well thanks to your tweak that's as simple as updating a single pref. ;)

**Closed** 2018-11-07 05:45 UTC

**Comment by leafcutterant** [comment] 2018-11-07 14:37
I updated Waterfox, the banner disappeared, but I still can't edit posts and comments on Github.

**Comment by wolfbeast** [comment] 2018-11-07 16:01
@leafcutterant This repository has nothing to do with Waterfox. Kindly direct your issue towards the correct repository.

**Comment by grahamperrin** [comment] 2018-11-07 16:03
@leafcutterant this is not a Waterfox support area. In Waterfox areas, please see: 

1. the pull request linked from https://github.com/MoonchildProductions/UXP/issues/864#issuecomment-436311167 above
2. **User Agent** ▶ https://www.reddit.com/comments/9drjqx/-/e94m0yv/

**Comment by leafcutterant** [comment] 2018-11-07 16:04
Apologies, I have mistaken this issue for another.

**Comment by Felipefpl** [comment] 2018-11-10 16:19
Thanks for everyone who replied to help and for wolfbeast for the fix, really kind of you. :)

Unfortunately a small problem i forgot to report still remains, i cant see the "tooltips" that are shown when hovering a commit with too many written words, i can see the "tooltip" when hovering an issue which contains the blue color though...

![no tooltip](https://user-images.githubusercontent.com/5569804/48303614-4aec8300-e4f3-11e8-9f7a-14f5a08433a3.jpg)

**Comment by JustOff** [comment] 2018-11-10 16:38
IFAIK there are no such tooltips in any browsers.

**Comment by Felipefpl** [comment] 2018-11-10 17:30
Sorry to disagree but this happened here when hovering a commit with too many words, i know you can click the 3 dots to open and read everything but this is a lost feature. ;)

**Comment by kn-yami** [comment] 2018-11-10 17:40
I can not get those commit message popup to display in Chrome. The only that Chrome Developer Console says is `As part of an experiment, Chrome temporarily shows only the lock icon in the address bar. Your SSL certificate with Extended Validation is still valid.`, with while worrying is of course unrelated.

**Comment by Felipefpl** [comment] 2018-11-11 11:03
kn-yami - i see, i am wondering if github's owners could have removed this feature themselves.... i hope they didnt. :/
