### ISSUE TITLE
Remove sites allowed to store data offline doesn't work

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#783] opened 2018-09-22 08:12 UTC
Advanced >> Network >> domains allowed to store data for offline use.

Selecting and removing doesn't work, FE vs BE problem from the move to UXP, most likely.

**Console error:**
```
Error: TypeError: BrowserUtils.principalFromOrigin is not a function
Source File: chrome://browser/content/preferences/advanced.js
Line: 454
```

**Comment by THEtomaso** [comment] 2018-09-22 09:58
Duplicate of this one?:
https://github.com/MoonchildProductions/UXP/issues/734/

**Comment by wolfbeast** [comment] 2018-09-22 11:29
Yup.

**Closed** 2018-09-22 11:29 UTC
Labels: App: Pale Moon, Bug, Duplicate
