### ISSUE TITLE
Make precompilation of Sync modules work

### ISSUE THREAD

**Issue by g4jc** [MoonchildProductions/UXP#1208] opened 2019-08-10 04:28 UTC
This is a minor bug that was introduced when backporting the [Tycho Weave](https://github.com/MoonchildProductions/UXP/commit/0c47c83e1b3b7d95681a43fbb0de0e17b2cd5b25#diff-3340b045733fd864c3822bf29f19c3a1R311) sync client.

`JavaScript error: resource://gre/modules/services-sync/service.js, line 302: TypeError: Svc.Prefs is undefined`

It should be defined or removed if it is not needed. Caught during the packaging process of omni.jar

**Comment by wolfbeast** [comment] 2019-08-10 08:57
`Svc.Prefs.*` is used throughout the sync client. It's most definitely needed.
it is defined in the imported module `util.js` as `Svc.Prefs = new Preferences(PREFS_BRANCH);` so there's no reason for it erroring (and certainly not for it erroring just on that line, either).

Can you provide more information?

**Comment by g4jc** [comment] 2019-08-10 14:02
STR:
- After a successful ./mach build, run ./mach package.
- All applications fail with said error message, but it does not appear to affect usability hence the bug appears to be minor.
(I do not personally use Sync, so perhaps it could be sign a more serious bug for those users)

[Basilisk Package Log](https://dpaste.de/w5ew/raw) and [Icedove-UXP Build Log](https://dpaste.de/OY7F/raw) showing the same error during the packaging process.

**Comment by wolfbeast** [comment] 2019-08-10 23:39
It's known that precompilation does not always succeed on all modules because of the rather simplistic nature of the precompilation script. This is non-breaking because all it will do when it fails at that step is not have a precompiled version of the script baked into omni.ja and it will be JIT compiled on first use.

So, this is a non-issue, really.

**Comment by wolfbeast** [comment] 2019-08-15 06:34
Looking at the build log, the issue is actually that `util.js` aborts on:
```
 0:06.63 *************************
 0:06.63 A coding exception was thrown and uncaught in a Task.
 0:06.63 
 0:06.63 Full message: TypeError: invalid path component
 0:06.63 Full stack: join@resource://gre/modules/osfile/ospath_unix.jsm:90:13
 0:06.63 this.Utils.jsonLoad<@resource://services-sync/util.js:324:16
 0:06.63 TaskImpl_run@resource://gre/modules/Task.jsm:319:42
 0:06.63 TaskImpl@resource://gre/modules/Task.jsm:277:3
 0:06.63 asyncFunction@resource://gre/modules/Task.jsm:252:14
 0:06.63 loadChangedIDs@resource://gre/modules/services-sync/engines.js:104:5
 0:06.63 Tracker@resource://gre/modules/services-sync/engines.js:53:3
 0:06.63 ClientsTracker@resource://gre/modules/services-sync/engines/clients.js:446:3
 0:06.63 get _tracker@resource://gre/modules/services-sync/engines.js:664:19
 0:06.63 Engine@resource://gre/modules/services-sync/engines.js:624:3
 0:06.63 SyncEngine@resource://gre/modules/services-sync/engines.js:707:3
 0:06.63 ClientEngine@resource://gre/modules/services-sync/engines/clients.js:40:3
 0:06.63 _registerEngines@resource://gre/modules/services-sync/service.js:448:26
 0:06.63 onStartup@resource://gre/modules/services-sync/service.js:343:5
 0:06.63 @resource://gre/modules/services-sync/service.js:1603:1
 0:06.63 load_modules_under@/home/user/Projects/hyperbola/icedove-uxp/mozilla/toolkit/mozapps/installer/precompile_cache.js:75:7
 0:06.63 precompile_startupcache@/home/user/Projects/hyperbola/icedove-uxp/mozilla/toolkit/mozapps/installer/precompile_cache.js:86:3
 0:06.63 @-e:1:1
 0:06.63 
 0:06.63 *************************
```
without that module, Svc.Prefs never gets set, and services-sync aborts as well.
So, looking into the "invalid path component" error should solve this, but I do believe that has been an error for a very long time.

**Comment by wolfbeast** [comment] 2019-08-15 07:31
Nope, that's not it. Disregard my previous comment.
Although that error should be fixed anyway (it can throw by design so it should be in a try/catch anyway).

The problem is that it's trying to use `Svc.Prefs` in a getter. That will get evaluated before startup.

I'm actually trying to find a reason why this getter and setter are there; Sync will not do anything unless specifically set up to do so and at least one an engine is enabled, so there's no need for this "master switch" to force it disabled based on engines being disabled. We can remove this, simplify the code, and get rid of an observer in the process ;)

**Comment by wolfbeast** [comment] 2019-08-15 07:32
Taking this as I have a good idea how to do this.

**Comment by wolfbeast** [comment] 2019-08-15 08:05
@g4jc You may need some front-end code change in `/components/preferences/[in-content/]sync.(js|xul)` if you still have the hidden pref there with an `onPreferenceChanged` handler.

**Comment by wolfbeast** [comment] 2019-08-15 08:49
Can you let me know how it behaves with these changes?

**Comment by wolfbeast** [comment] 2019-08-18 13:11
Confirmed through IRC.

**Closed by wolfbeast** 2019-08-18 13:11 UTC
Labels: C: Sync
