### ISSUE TITLE
Mixed-mode handling (web compatibility)

### ISSUE THREAD

**Issue by THEtomaso** [MoonchildProductions/UXP#907] opened 2018-12-12 19:58 UTC
### Issue:
Blank page (Blocked loading mixed active content)

### Example:
`https://www.clickondetroit.com/in-the-d/`

### Mozregression results:
* **Last bad: Firefox v54.0a1 (2017-02-09)**
* **First good: Firefox v54.0a1 (2017-02-10)**

Changelog for Firefox v54.0a1 (2017-02-10):
`http://forums.mozillazine.org/viewtopic.php?f=23&t=3027278/`

**Comment by mattatobin** [comment] 2018-12-12 20:17
Mixed-mode causes site JS to fail.. Use http instead.

**Comment by JustOff** [comment] 2018-12-12 20:34
Last bad: [firefox-54.0a1.en-US.win32.zip (20170209030214)](http://ftp.mozilla.org/pub/firefox/tinderbox-builds/mozilla-central-win32/1486638134/firefox-54.0a1.en-US.win32.zip)
First good: [firefox-54.0a1.en-US.win32.zip (20170209070421)](http://ftp.mozilla.org/pub/firefox/tinderbox-builds/mozilla-central-win32/1486652661/firefox-54.0a1.en-US.win32.zip)
Pushlog: [b772e0f41385 - 4dfd0d2d5dd3](https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=b772e0f4138540113e91a46c99bb0d14ecc8acca&tochange=4dfd0d2d5dd3b640d46ee405af7523e37545c155)

**Comment by mattatobin** [comment] 2018-12-12 20:36
I already TOLD you it is because of it trying to load mixed active content...

```
Timestamp: 12/12/2018 3:35:28 PM
Error: Blocked loading mixed active content “http://chevydetroit.com/inthed/?pmc=WDIV-ITD”
Source File: https://www.clickondetroit.com/in-the-d
Line: 0

Timestamp: 12/12/2018 3:35:29 PM
Error: NS_ERROR_UNEXPECTED: 
Source File: https://www.clickondetroit.com/in-the-d
Line: 1
```

On `HTTP` it isn't a problem and loads properly.

**Comment by JustOff** [comment] 2018-12-12 20:59
@mattatobin, please, don't take everything personally, I just trying to understand why it works after the mentioned change even with `block_active_content = true`, and I’ve failed so far.

**Comment by mattatobin** [comment] 2018-12-12 21:02
Because you can't load active content from `HTTP` on an `HTTPS` site.. It breaks security and by default it is blocked.

This is web developer 101 stuff here.

**Comment by THEtomaso** [comment] 2018-12-12 21:14
I don't know about coding, so I'd appreciate it if we kept things calm here.

The problem might very well be the "mixed-mode" issue that you pointed out, mattatobin.
I saw that in the console too.
But since I've seen that error many times, without it ever having caused such a obvious problem, I assumed that "NS_ERROR_UNEXPECTED" was the perp.

Nevertheless, the "last bad" / "first good" result in my first post is correct, so this is something that HAS been fixed in Firefox!
Just give it a try yourself.

--

> Last bad: firefox-54.0a1.en-US.win32.zip (20170209030214)
First good: firefox-54.0a1.en-US.win32.zip (20170209070421)

Sorry JustOff, but both of those builds fails to load the page from my end.

**Comment by JustOff** [comment] 2018-12-12 21:14
I'm trying to understand why **it works** (the page is rendering correctly, although it should not) after the [mentioned change](https://github.com/MoonchildProductions/UXP/issues/907#issuecomment-446734176),  regardless of the mixed active content restrictions.

**Comment by JustOff** [comment] 2018-12-12 21:32
@THEtomaso, thanks, I fixed the [regression range](https://github.com/MoonchildProductions/UXP/issues/907#issuecomment-446734176), could you please verify?

**Comment by THEtomaso** [comment] 2018-12-12 21:49
> Last bad: firefox-54.0a1.en-US.win32.zip (20170209070421)
First good: firefox-54.0a1.en-US.win32.zip (20170209070522)

Confirmed! :)

**Comment by THEtomaso** [comment] 2018-12-12 21:52
At least, all "mixed content" setting in about:config seems to be identical between those builds.

**Comment by THEtomaso** [comment] 2018-12-12 22:05
@JustOff:
Think I might have found it:
`https://bugzilla.mozilla.org/show_bug.cgi?id=1328460`

**Comment by JustOff** [comment] 2018-12-12 22:10
All that I was able to detect by this moment is that before [this change](https://github.com/MoonchildProductions/UXP/issues/907#issuecomment-446734176), `301` responses to `http` were blocked as a mixed active content, and after that they are not blocked anymore.

**Comment by THEtomaso** [comment] 2018-12-12 22:15
OK.
The fix that I refered to in my previous post is listed amongst the changes for v54.0a1 (2017-02-10), and it involves some changes to mixed-content handling.
..so I thought it might be worth checking out.

**Comment by JustOff** [comment] 2018-12-13 21:37
Today `www.clickondetroit.com` has changed the way it responds to `http/https` requests, now it is trying to redirect https to http, so further investigation of the problem seems impossible.

Just in case, I will leave here links to the bugs that may be related to the initial problem, which I managed to find out but did not fully check yesterday:

https://bugzilla.mozilla.org/show_bug.cgi?id=1336802 (this is in the range above)
https://bugzilla.mozilla.org/show_bug.cgi?id=1312954
https://bugzilla.mozilla.org/show_bug.cgi?id=1246540

I'm afraid at the moment we can hardly do something else useful here.

**Comment by THEtomaso** [comment] 2018-12-13 21:48
When connecting from my location, I don't see any difference compared to yesterday.
For me, it's still HTTPS, the page refuses to load, and the same errors are listed in the console.

**Comment by JustOff** [comment] 2018-12-13 22:06
Yesterday all requests to http were redirected to https, but 301 redirects were handled differently before and after the [range above](https://github.com/MoonchildProductions/UXP/issues/907#issuecomment-446734176).

Today is the opposite, and recent Firefox and Chrome are redirecting to `http://www.clickondetroit.com/in-the-d/` using this inline code:
```
(function(){if(document.location.protocol==="https:"&&document.location.hostname!="gmg.lakana.com"){document.location.protocol="http:"}})();
```
However, in Pale Moon and Firefox before the range this redirect does not work, because of some extra crazy code at the beginning of the document that halts and prevents further execution. And since the page source is one line wrapped I see no way to find out what exactly is the culprit.

**Comment by wolfbeast** [comment] 2018-12-15 11:07
So why all this noise for something straightforward?
If Firefox loads this page then it is violating mixed-mode restrictions. The page clearly tries to load mixed-mode content for its main article here:
```HTML
<div class="journal-content-article" id="article_10154_28243_165001713_1.4"> <!-- Added by BB for END-287 --> <style type="text/css">@media screen and (max-width:700px){.container{width:100%;padding:0}.portlet-column-only{padding:0}}</style> <iframe marginheight="0" marginwidth="0" scrolling="auto" src="http://chevydetroit.com/inthed/?pmc=WDIV-ITD" frameborder="0" width="100%" height="2530px"></iframe> </div>
```
Loading an `<iframe>` over http in an https document breaks security.

This has nothing to do with 301 redirects.

The other issue pointed out is that location.protocol might not be acting correctly (unrelated to the mixed mode issue) which would be [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1328894) which does fall within the fix range. 

Off-topic: @THEtomaso and others, please if you quote URLs do NOT make them unclickable by code-quoting them; it makes it really aggravating to follow the links.

**Comment by wolfbeast** [comment] 2018-12-15 11:31
Opened #910 for the location.protocol bug. Closing this one since there's nothing wrong with mixed mode blocking.

**Closed** 2018-12-15 11:31 UTC
Labels: Invalid

**Comment by THEtomaso** [comment] 2018-12-15 11:34
> Loading an <iframe> over http in an https document breaks security.

Thanks for elaborating, wolfbeast.
mattatobin was right in his assumption then:

> how do you know it isn't just Firefox changing the pref or relaxing restrictions to connect and display at any costs..

--

> please if you quote URLs do NOT make them unclickable by code-quoting them; it makes it really aggravating to follow the links.

Most bug trackers @ GitHub tells us to do this.
..but I'll try to remember not to do it here then. :)

**Comment by wolfbeast** [comment] 2018-12-15 11:37
> Most bug trackers @ GitHub tells us to do this.

I don't see why. URL magic making links clickable is a useful feature to have in an issue tracker. i don't see why devs would be opposed to it.

**Comment by wolfbeast** [comment] 2018-12-16 13:44
As an aside on-topic, the in-line code @JustOff quoted is actually incorrect too -- so another strike for the web designers making it work more by chance than on purpose on the browsers it does:
`document.location.protocol==="https:"` -- according to the spec a protocol is a URI scheme and should never include a `:` in it; so because this fails in later versions of Firefox that strip the `:` from `location.protocol` according to the spec, it will take a different code path on the site (but clearly not by intent).

This is why #910 will also fix this for us, because it makes the script error the same way.

**Comment by JustOff** [comment] 2018-12-16 14:16
> according to the spec a protocol is a URI scheme and should never include a `:`

This `clickondetroit.com` code is really messy, but it seems the problem is not in comparison, but in assignment. If you open the console on this page and type `document.location.protocol` all Pale Moon, Firefox or Chrome return `"http:"`, but Pale Moon without #910 fails on `document.location.protocol = "http:"`, while other browsers just strip `:`. However, this all looks really weird to me.

**Comment by JustOff** [comment] 2018-12-16 18:39
MDN just redirects https://developer.mozilla.org/en-US/docs/Web/API/Location/protocol to `HTMLHyperlinkElementUtils`, and see also https://developer.mozilla.org/en-US/docs/Web/API/Location:

```
Location.protocol
    Is a DOMString containing the protocol scheme of the URL, including the final ':'.
```

**Comment by wolfbeast** [comment] 2018-12-16 20:42
You're correct. location.protocol does include the `:` in the getter's response.
I'm guessing they are feeding an entire URL to the setter in that case, then, which we initially refused because it's invalid, but the spec says should be stripped.
