### ISSUE TITLE
Pale Moon on Linux does not start due to missing libmozgtk.so

### ISSUE THREAD

**Issue by adeshkp** [MoonchildProductions/UXP#179] opened 2018-04-15 18:00 UTC
I'm using CentOS 7 as a build system and Basilisk from moebius works just fine, so it should not be a system issue.
```
$ /tmp/exp/palemoon/palemoon-bin --no-remote --profile /tmp/exp/npmprofile/
XPCOMGlueLoad error for file /tmp/exp/palemoon/libmozgtk.so:
/tmp/exp/palemoon/libmozgtk.so: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
code 255
```

**Comment by mattatobin** [comment] 2018-04-15 18:39
Is it in dist or just not being packaged?

**Comment by adeshkp** [comment] 2018-04-15 18:55
It is not in dist -- not a packaging issue.

**Comment by trav90** [comment] 2018-04-15 19:06
Can't reproduce here - I'm typing this using a fresh build of Pale Moon built from tip of master.

**Comment by trav90** [comment] 2018-04-15 19:11
@adeshkp are you building with GTK2 or GTK3?

**Comment by trav90** [comment] 2018-04-15 19:27
UXP defaults to building with GTK3 unless GTK2 is explicitly specified in mozconfig with —enable-default-toolkit=cairo-gtk2

**Comment by mattatobin** [comment] 2018-04-15 19:43
I know why the lib isn't being packaged..

http://xref.palemoon.org/uxp-trunk/source/application/palemoon/installer/Makefile.in#37
vs 
http://xref.palemoon.org/uxp-trunk/source/browser/installer/Makefile.in#30

I'll fix it after I .. slowly get testing done in my VM.

**Comment by mattatobin** [comment] 2018-04-15 20:29
In my test GTK2 is perfectly fine in its packaged form. I have also https://github.com/MoonchildProductions/UXP/commit/4cc139ccb85e1119be54ab0a620476208df9cc29 and building GTK3 now.

CentOS 7

**Comment by mattatobin** [comment] 2018-04-15 22:53
I have no idea why it only seemed to matter sometimes but it should all be fixed now..

**Closed** 2018-04-16 12:34 UTC
Labels: Platform: Linux
