### ISSUE TITLE
Crash at assertion "Could not find EV root in NSS storage" in debug build : ExtendedValidation.cpp#1295

### ISSUE THREAD

**Issue by g4jc** [MoonchildProductions/UXP#664] opened 2018-07-22 01:36 UTC
I bumped into this [4 year old unsolved mozbug](https://bugzilla.mozilla.org/show_bug.cgi?id=994859) when building UXP with mozconfig settings: --enable-debug --disable-optimize (affects seamonkey, thunderbird, and possibly other applications calling certverifier)

    Assertion failure: iEV < NUM_TEST_EV_ROOTS (Could not find built-in EV root), at ~/thunderbird-52.2.0/mozilla/security/certverifier/ExtendedValidation.cpp:1295

http://xref.palemoon.org/uxp-trunk/source/security/certverifier/ExtendedValidation.cpp#1295

Temporary solution is to remove the entire debug check, but if it is needed it may be nice to fix it now that NSS is embedded.

**Comment by janekptacijarabaci** [comment] 2018-07-22 05:42
Dupe of #631

**Closed** 2018-07-22 13:35 UTC
