### ISSUE TITLE
palemoon-28.0.0 ignores fontconfig font preferences

### ISSUE THREAD

**Issue by l29ah** [MoonchildProductions/UXP#736] opened 2018-08-28 12:12 UTC
I have an option to pick my favourite font in my `~/.config/fontconfig/fonts.conf` that works everywhere, including firefox-esr and palemoon-27, but palemoon-28 ignores it. Simplified reproducer:
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
	<match>
		<test name="prgname" compare="eq" qual="any">
			<string>palemoon</string>
		</test>
		<edit name="family" mode="prepend_first" binding="strong">
			<string>xos4 Terminus</string>
			<string>Fixed</string>
		</edit>
	</match>
</fontconfig>
```

**Comment by wolfbeast** [comment] 2019-08-20 09:13
Asking for Linux people on the forum to provide more info

**Comment by Kokokokoka** [comment] 2019-08-20 10:09
Can reproduce with the above rule.
but this works for me:
`<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  
  <alias>
    <family>serif</family>
    <prefer><family>xos4 Terminus</family></prefer>
  </alias>
  <alias>
    <family>sans-serif</family>
    <prefer><family>xos4 Terminus</family></prefer>
  </alias>
  <alias>
    <family>sans</family>
    <prefer><family>xos4 Terminus</family></prefer>
  </alias>
    <alias>
    <family>monospace</family>
    <prefer><family>xos4 Terminus</family></prefer>
  </alias>
 <alias>
    <family>Arial</family>
    <prefer><family>xos4 Terminus</family></prefer>
  </alias>
  <alias>
    <family>Helvetica</family>
    <prefer><family>xos4 Terminus</family></prefer>
  </alias>
 <alias>
    <family>Verdana</family>
    <prefer><family>xos4 Terminus</family></prefer>
  </alias>
   <alias>
    <family>Times New Roman</family>
    <prefer><family>xos4 Terminus</family></prefer>
  </alias>
 <alias>
    <family>Courier New</family>
    <prefer><family>xos4 Terminus</family></prefer>
  </alias>
</fontconfig>`

**Comment by l29ah** [comment] 2019-08-20 11:27
> And manual selection of xos4 Terminus in Tools->Prefs->advanced works

No idea how to reach this, i have nothing in the `Advanced` tab about fonts, but `Preferences -> Content -> Default font` doesn't seem to have any effect.

**Comment by wolfbeast** [comment] 2019-08-20 12:08
> No idea how to reach this, i have nothing in the Advanced tab about fonts, but Preferences -> Content -> Default font doesn't seem to have any effect.

Try `Preferences` -> `Content` -> Under Fonts & Colors `Advanced`
Select the character set you want to change fonts for at the top (UTF-8 = "Other writing systems") and change the appropriate fonts.

**Comment by RoestVrijStaal** [comment] 2019-08-20 18:38
@l29ah Which distro do you use?

**Comment by l29ah** [comment] 2019-08-20 21:32
> Try Preferences -> Content -> Under Fonts & Colors Advanced
> Select the character set you want to change fonts for at the top (UTF-8 = "Other writing systems") and change the appropriate fonts.

Changed everything to Terminus for both Latin and Other, no effect on google and github at least.

> @l29ah Which distro do you use?

Gentoo Linux.

**Comment by kerframil** [comment] 2019-08-20 22:00
I see that xos4 Terminus is mentioned, which is a bitmapped font. As of pango-1.44, support for native bitmapped (and Type 1) fonts [has been completely removed](https://blogs.gnome.org/mclasen/2019/05/25/pango-future-directions/). Right now, this affects users of Arch Linux, albeit not Gentoo yet. Still, anyone evaluating this issue should just keep in mind that, given the aforementioned version of pango, it will be impossible to render a font such as xos4 Terminus in Pale Moon unless it is converted to the OpenType format.

**Comment by l29ah** [comment] 2019-08-20 22:25
> As a general direction, we want to move Pango towards (horizontally) unhinted rendering, combined with subpixel positioning. Other platforms are already doing this. And it gives us resolution-independent layout that is better suited for scalable apis and OpenGL rendering.

Ouch. I think they are making bitmap fonts worthless by enforcing blurry, pixel-independent rendering of whatever you throw at them. So either you have a huge letters/resolution where it doesn't really matter or an unreadable haze instead of the glyphs :/

**Comment by wolfbeast** [comment] 2019-08-20 23:09
So, do I understand this correctly and it's an O.S. issue and not a UXP issue?

**Comment by l29ah** [comment] 2019-08-20 23:24
No.

**Comment by wolfbeast** [comment] 2019-08-20 23:29
So which Firefox ESR are you talking about then that works?

**Comment by l29ah** [comment] 2019-08-20 23:43
I don't quite remember which one it was a year ago, probably 52.

**Comment by wolfbeast** [comment] 2020-03-24 07:54
Closing this - not a browser/platform issue.

**Closed by wolfbeast** 2020-03-24 07:54 UTC
Labels: Invalid, Platform: Linux
