### ISSUE TITLE
Rendering issues on mlb.com

### ISSUE THREAD

**Issue by hawkeye116477** [MoonchildProductions/UXP#1235] opened 2019-09-28 10:03 UTC
Go to `mlb.com` and you will see the problem.

On Firefox
![Screenshot_20190928_120049](https://user-images.githubusercontent.com/19818572/65814848-a7c65a00-e1e7-11e9-854b-a2fee0db54ea.png)

On Basilisk
![Screenshot_20190928_120142](https://user-images.githubusercontent.com/19818572/65814854-c2003800-e1e7-11e9-8e66-02cbbed09ded.png)

Also on https://www.mlb.com/phillies/schedule/list it lacks table.

Mozregression result:
- Last bad: Firefox **v58.0a1 (2017-10-23)**
- First good: Firefox **v58.01 (2017-10-24)**

Puslog: https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=9056f2ee492fa481aa86146aba236c074628e9fd&tochange=a124f4901430f6db74cfc7fe3b07957a1c691b40

**Comment by g4jc** [comment] 2019-09-28 19:57
Regarding the missing table:
`[JavaScript Error: "TypeError: a.toLowerCase is not a function" {file: "https://www.mlbstatic.com/mlb.com/builds/site-core/e6d4545e6c9c1eca9aca6ca831dfd979499eff2b_1569338686/scripts/site-desktop.js" line: 26}]`

Possibly https://bugzilla.mozilla.org/show_bug.cgi?id=638054

**Comment by wolfbeast** [comment] 2019-09-29 12:41
If that BZ bug is the cause then mlb should hire a better webmaster that doesn't try to use non-standard debugging functions on productions sites.

**Comment by g4jc** [comment] 2019-10-25 22:59
Since the a fore mentioned moz-bug 638054 was confirmed on the [forum](https://forum.palemoon.org/viewtopic.php?f=3&t=22973&start=20#p176796) do we want to try and get in touch with @itspolo to turn debugging off on the release MLB website (the real fix), or do we want to [break Dev Tools/Firebug](https://bugzilla.mozilla.org/show_bug.cgi?id=934669#c7) and backport this work-around?

**Comment by mattatobin** [comment] 2019-10-25 23:04
I'd say get the minor league webmaster to disable their debug mode..

**Comment by wolfbeast** [comment] 2019-10-26 01:55
So ultimately, the problem is that the webmaster is not using a production configuration on their production website.
HOWEVER, if watch/unwatch is non-standard, deprecated and actually breaking things, then it means it's also our problem.

So we have an interop issue here. For the browser to work on these websites, if server-side debugging is enabled on it, we have to break our debugging capabilities. And the other way around, too: for the website to work on a browser with debugging capabilities, the website owner has to break their debugging capabilities; but with the critical note that production websites _really_ shouldn't have debugging features enabled.

**Comment by g4jc** [comment] 2019-10-26 02:32
Right. I suppose one alternative way to mitigate the interop is use the deprecate warning method and stuff it behind a pref. It can be off by default - and then debuggers would have to turn it on, while the average user can blissfully load the bugged/debug pages without issue.

**Comment by wolfbeast** [comment] 2019-10-26 02:48
I looked more into this; we should just remove it. It's non-standard, none of the other browsers offer it, our devtools don't use it any longer, and assuming Firebug has also moved on to using alternatives (since the "breaking" comment was from 2013 and a lot has changed since then).
Stuffing it behind a pref is not really possible because it has many JS hooks that will get called if present, and my guess is the sites suffering from this will trip over having the internal JS definitions existing in the first place in content that can't be redefined (erroring out when trying to define their own `watch()` or `unwatch()` functions on objects). Since it's not a prefable IDL API it can't be simply disabled, and since it intercepts calls/proxies (by design) it can't be made into something that way either.

**Comment by wolfbeast** [comment] 2019-10-27 01:19
Someone please build from tip of master and test the site now #1257 has been fixed?

**Comment by SpockFan02** [comment] 2019-10-27 03:28
It's fixed, the menu at the top is visible and works, and the schedule page works fine now too.

**Comment by g4jc** [comment] 2019-10-27 22:17
Confirming fixed on GNU/Linux as well. 👍

**Closed** 2019-10-28 03:08 UTC
Labels: Fixed, Verified

**Comment by cblknittights** [comment] 2019-10-30 12:55
This breaks IHG in Palemoon when released to users.

https://github.com/cblknittights/ImageHost-Grabber/issues/18

watch/unwatch is used to get the URL's of the images to grab... 

This is used due to:
requestObj class:  It's necessary to create a class that encompasses the XMLHttpRequest
 * class.  Each new instance of requestObj will create a new instance of XMLHttpRequest.
 * What this does is it allows the XMLHttpRequest object to access data that is not part
 * of the XMLHttpRequest class definition.  The difference between this and adding a property
 * or member on the fly (i.e. object.whatever = somestuff), is that the data is guaranteed to
 * be accessible using this technique.  Whereas, when adding members on the fly, XMLHttpRequest
 * **_had a bad tendency of losing the data that was assigned to it on the fly._**
 */

**Comment by wolfbeast** [comment] 2019-10-30 21:23
As a workaround, you can incorporate watch/unwatch on objects as a shim (using defineproperty) in your extension if you don't want to rewrite it using getters/setters or the proxy object.
