### ISSUE TITLE
Browser update system requires elevated account

### ISSUE THREAD

**Issue by Gnat008** [MoonchildProductions/UXP#657] opened 2018-07-20 21:17 UTC
The update mechanism requiring elevated privileges is expected, of course. However, it must be run by an administrator account (on Windows, when installed to a location such as Program Files, or on Linux when installed in, say /opt) to actually download and install the update, or force you to download the new version yourself, which totally defeats the point of having the option in the first place.

It would be great from a UX standpoint if it could mirror Firefox's process when opening the About window, where the browser checks for and downloads the update, then prompts the user to restart and actually update, at which point it can ask for elevation (at least on Windows, with UAC; I'd imagine you could do something similar with `sudo` on *NIX).

**Comment by khronosschoty** [comment] 2018-07-20 22:46
I've used Discord on Pale Moon UXP without issue, but I will investigate
using Basilisk... that said, I do suspect the issue is not with
Basilisk.

**Comment by kn-yami** [comment] 2018-07-20 22:54
@khronosschoty you wanted to comment on #658, right?

**Comment by khronosschoty** [comment] 2018-07-20 23:07
whoops sorry yes

**Comment by wolfbeast** [comment] 2018-07-21 06:02
I don't see the problem. The updater (updater.exe) will ask for elevation when it's time to update.

**Comment by Gnat008** [comment] 2018-07-21 16:51
@wolfbeast No, it doesn't, unless you're talking about something different. Going to the About dialog only tells you to go to the website, and the updater window that appears while browsing does not request elevation. It also tells you to go to the website to re-download.

**Comment by Nuck-TH** [comment] 2018-07-21 16:59
@Gnat008 look for problem on your system. Updating Pale Moon UXP on Windows 7 works as intended for me. About window and updater window do not need elevation, as wolfbeast said - it is only requested by updater.exe after it is downloded.

**Comment by Gnat008** [comment] 2018-07-21 17:05
On Windows 10 (1803 update) on a non-administrator account.

About dialog:
![image](https://user-images.githubusercontent.com/5157277/43038395-2e13d220-8ce6-11e8-800a-5e81a0cdf84c.png)

I'll post the update popup window once it appears, but it does not ask for elevation.

**Comment by wolfbeast** [comment] 2018-07-21 20:16
If you are running in a restricted/limited account then this is correct. It will only be able to notify you an update is available, but you will have to switch to an administrative account for the machine to update. The browser does a request to the OS and asks if the account it's run under has elevation privileges, and if not, then it will just notify/inform since that is all it is allowed to do.

A regular (non-restricted) account with elevation privileges will get the regular update button, and `updater.exe` will ask for UAC elevation to install the update.

**Comment by Gnat008** [comment] 2018-07-21 20:31
Hm. I wonder if there's a better flow for non-privileged accounts... Would it be possible for the About window to download the update or call `updater.exe`, which could (would?) then ask for elevation? I'm not a big C++/JS person, so I wouldn't know where to look in the code.

**Comment by mattatobin** [comment] 2018-07-21 22:29
There is not any kind of simple solution to this so I think it is best left unchanged. Bottom line is that in order for AUS to actually update your software you must be running under an administrative account.

**Comment by wolfbeast** [comment] 2018-07-22 00:48
@Gnat008 The flow you ask for is already present. It's just not a path taken when there is no reason to believe the user can elevate without logging in with different credentials. Performing downloads and launching an update process that is likely going to fail is in nobody's interest, which is why this different behavior for restricted accounts exists in the first place.

Closing this as WFM.

**Closed** 2018-07-22 00:49 UTC
Labels: C: Installer/Updater, Works for me

**Comment by Gnat008** [comment] 2018-07-22 00:59
I respect the decision, but you are aware that a UAC prompt for a non-admin account allows you to enter the username and password for an admin account, and this the program has elevated privileges?

**Comment by wolfbeast** [comment] 2018-07-22 01:43
> "It's just not a path taken when there is no reason to believe the user can elevate without logging in with different credentials."

The software has no way of knowing that the user sitting at the computer has administrative credentials available. It has to be assumed they do not, and therefore the administrative update task should not be started. I understand it's inconvenient if using on-the-fly administrative login is your workflow, but that is not a common workflow. All the more common is that restricted accounts are actually used by users who are not administrators. In that situation you don't want this process to download or launch anything that cannot reasonably be completed.

**Comment by Gnat008** [comment] 2018-07-22 02:06
Understood.
