### ISSUE TITLE
page elements not shown properly

### ISSUE THREAD

**Issue by Sa-Ja-Di** [MoonchildProductions/UXP#980] opened 2019-02-21 01:13 UTC
Forum thread opener
https://forum.palemoon.org/viewtopic.php?f=61&p=162235

reports that a page is not get shown properly - The elements under popular styles stay blank. Icons are shown for example in Chrome.

Console shows only one error:

Timestamp: 21.02.2019 00:06:05
Error: SyntaxError: invalid property id
Source File: https://maxst.icons8.com/_nuxt/icon/ven ... 4dd393f.js
Line: 2, Column: 28527
Source Code:
rn o["en-US"];if(t.url.indexOf("crowdin-overlay")>=0)return{...o["en-US"],locale:"zu-ZA"};const e=`https://${t.hostname|

**Comment by wolfbeast** [comment] 2019-02-21 09:40
Impossible to troubleshoot without the proper info. "This site doesn't work because error x in minified js blob y which may or may not be the cause" is not something we can work with.

**Comment by Sa-Ja-Di** [comment] 2019-02-21 13:34
Win-7-7 has added necessary info which are perhaps https://forum.palemoon.org/viewtopic.php?f=61&p=162258&sid=c78cc3c52cbd3fe44a4d96a2704c9d6c#p162258

Following pushlog show what is fix to this problem.

https://hg.mozilla.org/integration/mozi ... b22d429d0e

https://bugzilla.mozilla.org/show_bug.cgi?id=1339395

Testing done based to tinderbox builds (https://ftp.mozilla.org/pub/firefox/tin ... und-win64/)

build 1493911761 does not have problem with website while 1493911520 does.

**Comment by wolfbeast** [comment] 2019-02-21 23:57
Okay.
Duplicate of #802

**Closed by wolfbeast** 2019-02-21 23:57 UTC
Labels: Incomplete, More info needed
