### ISSUE TITLE
High CPU usage on 32bit platforms when left idle

### ISSUE THREAD

**Issue by g4jc** [MoonchildProductions/UXP#723] opened 2018-08-22 01:18 UTC
Creating this issue to track high CPU Usage on 32bit platforms. The bug is not reproducible on 64bit.
So far this bug has shown itself in Iceweasel-UXP and PaleMoon when running on 32bit.

I was able to reproduce this on a Linux VM with a 32bit distro set to a single CPU, and 1GB of ram.
I believe it to be the same bug affecting [Windows users of PM28](https://forum.palemoon.org/viewtopic.php?f=29&p=148995).

1. Start the browser application
2. Open a new tab and get the browser out of focus by using any other program and not clicking on the browser for 1 minute.
3. CPU usage will climb quickly until reaching and hanging at 100%

So far gdb has resulted in very little information other than it is hanging during an nsThread call. I have been unable to locate which call and had originally suspected a runaway Telemetry timer due to the requirement of waiting one minute prior to the hang. However,  removing those timers has had no affect.

Using the [Built-In Profiler](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler) may help here. More research is needed.

**Comment by wolfbeast** [comment] 2018-08-22 06:03
It's a runaway script which is not possible to pinpoint with the profiler (which you can't use since it's been removed due to entanglement with the crash reporter and telemetry). Firefox ESR52 suffers from the same.
It's an elusive problem - if you lower script execution times before the watchdog kicks in you'll get warnings thrown on internal scripts (mostly in bindings). I haven't been able to pinpoint the cause either.

**Comment by wolfbeast** [comment] 2018-09-02 07:41
Is this still an issue on v28.0.1? Just making sure this isn't a duplicate of what was solved in #739

**Comment by g4jc** [comment] 2018-09-06 01:43
@wolfbeast  Unable to reproduce since #739 has been fixed. Left it running on a debugger for some time to make sure. Appears to have solved on all applications - thanks! :+1:

**Comment by wolfbeast** [comment] 2018-09-07 18:17
There are a few things that are scheduled after idle time or x seconds after startup, not in the least loading and parsing/sanitizing system-available fonts and cache/history management. If you have a lot of installed fonts that can take significant processing.

**Comment by MihailZenkov** [comment] 2018-09-08 17:57
I have same problem on Linux with 32bit userspace + kernel 64bit. Not sure is it help but I have profile from sysprof (system-wide profiler): [pm_bug.syscap.log](https://github.com/MoonchildProductions/UXP/files/2363561/pm_bug.syscap.log)

**Comment by wolfbeast** [comment] 2018-09-08 19:10
I can't do anything with a proprietary binary log file format...

**Comment by wolfbeast** [comment] 2018-09-08 19:50
I don't, so I'll let someone on Linux look at it then.

**Closed** 2018-09-19 22:37 UTC
Labels: Bug, Performance

**Comment by wolfbeast** [comment] 2018-09-19 22:41
Nice catch on the conversion bug in the PR.
The issue being event loop -> idle state -> idle timer init at INT32_MAX -> conversion to msec causing overflow.
Overflow on i686 -> 0
Overflow on x86_64 -> arbitrary large value.

On 32-bit this would immediately re-arm the timer when expired, causing a fast spin loop for the timer and high CPU usage/thread blocking.

PR resolves this by making the initialization value 10 x seconds/day which won't overflow int32 when converted to msec.
