### ISSUE TITLE
Segmentation fault in Linux when resuming downloads

### ISSUE THREAD

**Issue by andreat** [MoonchildProductions/UXP#1337] opened 2019-12-25 10:12 UTC
Hi, I am facing a strange segmentation fault when using Pale Moon 28.8.0 in linux (openSUSE x86_64 Leap 15.0).

I downloaded the x64 tar.xz file from the Pale Moon website and I have found these steps to reproduce the segmentation fault:
1. (create a new user, so to use a completely clear profile)
2. execute Pale Moon and make Pale Moon to "Show my windows and tabs from last time" on startup
3. open the page https://www.springer.com/gp/computer-science/lncs/conference-proceedings-guidelines 
4. download one of the documents hosted on ftp (guidelines for proceeding authors or one of the templates zip files) on a new tab (Ctrl-click on the link)
5. in the download manager, cancel the download (in my case, I can cancel it before it actually starts, so the download manager shows 0 bytes downloaded and an unknown time remaining when I cancel the download)
6. in the download manager, click on the retry button to retry the cancelled download.

As soon as I retry the download, Pale Moon crashes with a segmentation fault.
The only message shown in the terminal is: "Segmentation fault (core dumped)" but I can't find the core dump or any message in the system logs.
If I try gdb, the information I get is:
`
Thread 1 "palemoon" received signal SIGSEGV, Segmentation fault.
0x00007ffff26c1b86 in ?? () from /opt/palemoon/libxul.so
`
and the (now frozen) Pale Moon window shows the restore session page.

The interesting thing is that sometimes, when I restart Pale Moon, I get another segmentation fault on the request to restore the previous session, that appears for very short time. If this happens, then it is going to happen again and again except that sometimes I get a prompt saying that Pale Moon is running in safe mode and that I can make permanent some changes. If I just click "Continue in Safe Mode", another segmentation fault happens. If I click Quit, Pale Moon terminates without problems and in some case this allows me to break the loop of segmentation faults.

If needed, I have a tar.gz of the profile where the loop of segmentation faults occur, if this helps when trying to debug the problem.

**Comment by g4jc** [comment] 2019-12-25 18:54
Unable to reproduce per steps (the download happens very quickly and unable to cancel it in time), however I do have a PaleMoon with debug symbols and would be interested in a copy of the corrupted profile to see if I can catch the SIGSEGV here.

Keep in mind there's also been issues with themes on some distros which cause unusual crashes as well, so without knowing your Desktop Environment I may not be able to reproduce.

**Comment by andreat** [comment] 2019-12-26 02:03
As desktop environment, I use LXDE. With the attached profile the crash happens also in LXQt, GNOME, Xfce, IceWM, TWM, enlightment and Plasma/KDE with their default setting: I just delete and recreate the user for each DE, then expand the profile, fix its ownership and run palemoon.
Usually this results in having the Session Restore window without SIGSEGV, but then by the steps in the first post, the crash reappears.

If I can get a version of Pale Moon with the debug symbols, I can use it in gdb to help in debugging (with some suggestion on the use of gdb, since I know only its very basic usage), in case the attached profile still doesn't show the SIGSEGV in your system.

[pm-sf.ZIP](https://github.com/MoonchildProductions/UXP/files/4001031/pm-sf.ZIP)

**Comment by wolfbeast** [comment] 2019-12-29 21:43
Why are debug symbols disabled in our Linux binaries to begin with?

**Comment by andreat** [comment] 2020-01-12 02:04
Just for reference: the crash happens also with version 28.8.1.

**Comment by wolfbeast** [comment] 2020-01-12 10:23
@trav90 Do you have an opportunity to look at what's going on here?

**Comment by zqqw** [comment] 2020-01-20 02:28
It segfaults for me if I have Isaac Schemm's pdf viewer installed.
[https://github.com/IsaacSchemm/pdf.js-seamonkey/releases](url)
I can open a clean profile, click on the latest pdf.js.xpi which installs. Then I try the first pdf link on that page and Pale Moon vanishes immediately, just from clicking on it. Without the pdf viewer the file downloads normally. gdb bt attached from my GTK3 debug build.
[pmcd.txt](https://github.com/MoonchildProductions/UXP/files/4084163/pmcd.txt)

**Comment by andreat** [comment] 2020-01-28 20:24
The attached profile still crashes with Pale Moon 28.8.2.

**Comment by andreat** [comment] 2020-03-24 15:59
Version 28.9.0 still crashing with the previously attached profile

**Comment by mattatobin** [comment] 2020-03-24 16:43
And?

**Comment by andreat** [comment] 2020-03-25 08:46
> And?

In bug reports I filed against other software, developers asked me to check whether the reported bugs were still applicable to the newer version of the software.

If you don't want me to check the issue with the newer versions of Pale Mon, just tell me.

**Comment by wolfbeast** [comment] 2020-03-25 09:41
Well over here we take the ore logical approach that as long as no work has been done on an issue, that it is still an issue. You can still check if it applies and report if it's fixed as part of continued development, but otherwise having a string of "still broken" "still broken" "yup, still broken" posts with every release are really rather pointless.

**Comment by trav90** [comment] 2020-03-25 11:56
I have looked at this a little bit, but so far haven't been able to reproduce the crash.

**Comment by wolfbeast** [comment] 2020-04-20 12:35
Please don't arbitrarily close issues without stated reason or comment.

**Comment by wolfbeast** [comment] 2020-04-24 08:11
Some work has been done on the download manager code which may have fixed this; since it can't be reproduced I'll close this for now for being inconclusive.

**Closed by wolfbeast** 2020-04-24 08:11 UTC
Labels: Crash, Incomplete, OS: Linux
